version: '3.8'

services:
  firebase-emulator:
    image: google/firebase-emulator
    ports:
      - '4000:4000'
      - '5000:5000'
      - '8080:8080'
      - '9099:9099'
    environment:
      - FIREBASE_DATABASE_EMULATOR_HOST=firebase-emulator:9000
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
    volumes:
      - ./firebase:/firebase
    command: firebase emulators:start --import=./firebase/seed --export-on-exit

  admin-web:
    build:
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile.admin_web
    ports:
      - '3000:3000'
    environment:
      - VITE_FIREBASE_EMULATOR_HOST=firebase-emulator:8080
      - NODE_ENV=development
    depends_on:
      - firebase-emulator
    volumes:
      - ./apps/admin_web:/app
      - /app/node_modules

volumes:
  firebase-data:
