// File generated by FlutterFire CLI.
// $ flutterfire configure
// flutter pub add firebase_core
// flutter pub add cloud_firestore
// flutter pub add firebase_auth
// flutter pub add firebase_storage
// flutter pub add firebase_messaging

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ12345', // TODO: Add your Firebase API Key
    appId: '1:123456789:android:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'aquacare-system', // TODO: Update with your Firebase project ID
    storageBucket: 'aquacare-system.appspot.com',
    databaseURL: 'https://aquacare-system.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ12345',
    appId: '1:123456789:ios:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'aquacare-system',
    storageBucket: 'aquacare-system.appspot.com',
    iosBundleId: 'com.aquacare.customerApp',
    databaseURL: 'https://aquacare-system.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ12345',
    appId: '1:123456789:web:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'aquacare-system',
    authDomain: 'aquacare-system.firebaseapp.com',
    storageBucket: 'aquacare-system.appspot.com',
    databaseURL: 'https://aquacare-system.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ12345',
    appId: '1:123456789:windows:abcdefghijklmnop',
    messagingSenderId: '123456789',
    projectId: 'aquacare-system',
    storageBucket: 'aquacare-system.appspot.com',
    databaseURL: 'https://aquacare-system.firebaseio.com',
  );
}
