// File generated by flutterfire configure
// This file uses Firebase Emulator for local development
// To use real Firebase, run: flutterfire configure --project=<your_firebase_project_id>

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  // Firebase Emulator configuration for local development
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'demo-aquacare-local',
    appId: '1:123456789:web:demo',
    messagingSenderId: '123456789',
    projectId: 'demo-aquacare-local',
    authDomain: 'localhost',
    storageBucket: 'demo-aquacare-local.appspot.com',
    measurementId: 'G-DEMO',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'demo-aquacare-local',
    appId: '1:123456789:android:demo',
    messagingSenderId: '123456789',
    projectId: 'demo-aquacare-local',
    databaseURL: 'http://localhost:9000',
    storageBucket: 'demo-aquacare-local.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-aquacare-local',
    appId: '1:123456789:ios:demo',
    messagingSenderId: '123456789',
    projectId: 'demo-aquacare-local',
    databaseURL: 'http://localhost:9000',
    storageBucket: 'demo-aquacare-local.appspot.com',
    iosBundleId: 'com.aquacare.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-aquacare-local',
    appId: '1:123456789:macos:demo',
    messagingSenderId: '123456789',
    projectId: 'demo-aquacare-local',
    databaseURL: 'http://localhost:9000',
    storageBucket: 'demo-aquacare-local.appspot.com',
    iosBundleId: 'com.aquacare.customer.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-aquacare-local',
    appId: '1:123456789:windows:demo',
    messagingSenderId: '123456789',
    projectId: 'demo-aquacare-local',
    authDomain: 'localhost',
    databaseURL: 'http://localhost:9000',
    storageBucket: 'demo-aquacare-local.appspot.com',
  );

  // Use Android config for mobile, web for web
  static const FirebaseOptions currentPlatform = android;
}
